Repository Pending-Name-21/arquitecture, pull requests merged in 2024-05, with the labels that each got.

#2 Frontend UMLs
  uml/frontend-software-system/collisions-subscribers.puml
  uml/frontend-software-system/game.puml
  uml/frontend-software-system/input-subscribers.puml
  uml/frontend-software-system/piece.puml
Labels: UML

#5 FFI approach design refactor
  workspace.dsl
Labels: architecture

#6 chore: created input-handler componentb
  uml/frontend-software-system/game-loop.puml
  uml/frontend-software-system/game-settings.puml
  uml/frontend-software-system/input-subscribers.puml
  uml/frontend-software-system/package.puml
  uml/frontend-software-system/piece.puml
  uml/frontend-software-system/process-input-handler.puml
  uml/frontend-software-system/update-handler.puml
  uml/frontend-software-system/update-stage-subscribers.puml
Labels: bridge

#7 Task 89: UML Render Handler
  uml/frontend-software-system/game-loop.puml
  uml/frontend-software-system/package.puml
  uml/frontend-software-system/piece.puml
  uml/frontend-software-system/render-handler.puml
  uml/frontend-software-system/update-handler.puml
Labels: bridge
